// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flappy.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class LoginInfo;
@class Message;
@class Route;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - FlappyRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface FlappyRoot : GPBRootObject
@end

#pragma mark - FlappyRequest

typedef GPB_ENUM(FlappyRequest_FieldNumber) {
  FlappyRequest_FieldNumber_Type = 1,
  FlappyRequest_FieldNumber_Latest = 2,
  FlappyRequest_FieldNumber_Msg = 3,
  FlappyRequest_FieldNumber_Login = 4,
};

/**
 * 请求
 **/
@interface FlappyRequest : GPBMessage

/** 类型 */
@property(nonatomic, readwrite) int32_t type;

/** 时间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *latest;

/** 消息 */
@property(nonatomic, readwrite, strong, null_resettable) Message *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

/** 登录信息 */
@property(nonatomic, readwrite, strong, null_resettable) LoginInfo *login;
/** Test to see if @c login has been set. */
@property(nonatomic, readwrite) BOOL hasLogin;

@end

#pragma mark - FlappyResponse

typedef GPB_ENUM(FlappyResponse_FieldNumber) {
  FlappyResponse_FieldNumber_Type = 1,
  FlappyResponse_FieldNumber_MsgArray = 2,
};

/**
 * 回复
 **/
@interface FlappyResponse : GPBMessage

/** 类型 */
@property(nonatomic, readwrite) int32_t type;

/** 消息 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Message*> *msgArray;
/** The number of items in @c msgArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgArray_Count;

@end

#pragma mark - KafkaMsg

typedef GPB_ENUM(KafkaMsg_FieldNumber) {
  KafkaMsg_FieldNumber_Type = 1,
  KafkaMsg_FieldNumber_RouteArray = 2,
  KafkaMsg_FieldNumber_Msg = 3,
};

/**
 * kafka消息
 **/
@interface KafkaMsg : GPBMessage

/** 类型 */
@property(nonatomic, readwrite) int32_t type;

/** 路由 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Route*> *routeArray;
/** The number of items in @c routeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger routeArray_Count;

/** 消息 */
@property(nonatomic, readwrite, strong, null_resettable) Message *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - Route

typedef GPB_ENUM(Route_FieldNumber) {
  Route_FieldNumber_UserId = 1,
  Route_FieldNumber_Device = 2,
  Route_FieldNumber_Pushid = 3,
};

/**
 * 路由
 **/
@interface Route : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *device;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pushid;

@end

#pragma mark - Message

typedef GPB_ENUM(Message_FieldNumber) {
  Message_FieldNumber_MessageId = 1,
  Message_FieldNumber_MessageSession = 2,
  Message_FieldNumber_MessageSessionType = 3,
  Message_FieldNumber_MessageSessionOffset = 4,
  Message_FieldNumber_MessageTableSeq = 5,
  Message_FieldNumber_MessageType = 6,
  Message_FieldNumber_MessageSend = 7,
  Message_FieldNumber_MessageRecieve = 8,
  Message_FieldNumber_MessageContent = 9,
  Message_FieldNumber_MessageSended = 10,
  Message_FieldNumber_MessageReaded = 11,
  Message_FieldNumber_MessageDate = 12,
  Message_FieldNumber_MessageDeleted = 13,
  Message_FieldNumber_MessageDeletedDate = 14,
};

/**
 * 消息
 **/
@interface Message : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageSession;

@property(nonatomic, readwrite) int32_t messageSessionType;

@property(nonatomic, readwrite) int32_t messageSessionOffset;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageTableSeq;

@property(nonatomic, readwrite) int32_t messageType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageSend;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageRecieve;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageContent;

@property(nonatomic, readwrite) int32_t messageSended;

@property(nonatomic, readwrite) int32_t messageReaded;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageDate;

@property(nonatomic, readwrite) int32_t messageDeleted;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageDeletedDate;

@end

#pragma mark - LoginInfo

typedef GPB_ENUM(LoginInfo_FieldNumber) {
  LoginInfo_FieldNumber_UserId = 1,
  LoginInfo_FieldNumber_Device = 2,
  LoginInfo_FieldNumber_Pushid = 3,
};

/**
 * 登录信息
 **/
@interface LoginInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *device;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pushid;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
