// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flappy.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Message;
@class ReqLogin;
@class ReqReceipt;
@class ReqUpdate;
@class Route;
@class Session;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - FlappyRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface FlappyRoot : GPBRootObject
@end

#pragma mark - FlappyRequest

typedef GPB_ENUM(FlappyRequest_FieldNumber) {
  FlappyRequest_FieldNumber_Type = 1,
  FlappyRequest_FieldNumber_Msg = 2,
  FlappyRequest_FieldNumber_Login = 3,
  FlappyRequest_FieldNumber_Update = 4,
  FlappyRequest_FieldNumber_Receipt = 5,
};

/**
 * 请求
 **/
@interface FlappyRequest : GPBMessage

/** 类型 */
@property(nonatomic, readwrite) int32_t type;

/** 聊天消息 */
@property(nonatomic, readwrite, strong, null_resettable) Message *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

/** 登录信息 */
@property(nonatomic, readwrite, strong, null_resettable) ReqLogin *login;
/** Test to see if @c login has been set. */
@property(nonatomic, readwrite) BOOL hasLogin;

/** 更新信息 */
@property(nonatomic, readwrite, strong, null_resettable) ReqUpdate *update;
/** Test to see if @c update has been set. */
@property(nonatomic, readwrite) BOOL hasUpdate;

/** 信息回执 */
@property(nonatomic, readwrite, strong, null_resettable) ReqReceipt *receipt;
/** Test to see if @c receipt has been set. */
@property(nonatomic, readwrite) BOOL hasReceipt;

@end

#pragma mark - FlappyResponse

typedef GPB_ENUM(FlappyResponse_FieldNumber) {
  FlappyResponse_FieldNumber_Type = 1,
  FlappyResponse_FieldNumber_MsgArray = 2,
  FlappyResponse_FieldNumber_SessionsArray = 3,
};

/**
 * 回复
 **/
@interface FlappyResponse : GPBMessage

/** 类型 */
@property(nonatomic, readwrite) int32_t type;

/** 消息 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Message*> *msgArray;
/** The number of items in @c msgArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgArray_Count;

/** 会话 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Session*> *sessionsArray;
/** The number of items in @c sessionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger sessionsArray_Count;

@end

#pragma mark - FlappyKafka

typedef GPB_ENUM(FlappyKafka_FieldNumber) {
  FlappyKafka_FieldNumber_Type = 1,
  FlappyKafka_FieldNumber_RouteArray = 2,
  FlappyKafka_FieldNumber_Msg = 3,
};

/**
 * 消息传递
 **/
@interface FlappyKafka : GPBMessage

/** 类型 */
@property(nonatomic, readwrite) int32_t type;

/** 路由 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Route*> *routeArray;
/** The number of items in @c routeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger routeArray_Count;

/** 消息 */
@property(nonatomic, readwrite, strong, null_resettable) Message *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - ReqLogin

typedef GPB_ENUM(ReqLogin_FieldNumber) {
  ReqLogin_FieldNumber_UserId = 1,
  ReqLogin_FieldNumber_Device = 2,
  ReqLogin_FieldNumber_Pushid = 3,
  ReqLogin_FieldNumber_Latest = 4,
};

/**
 * 登录信息
 **/
@interface ReqLogin : GPBMessage

/** 用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 设备信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *device;

/** 推送ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pushid;

/** 最后的tableSequece */
@property(nonatomic, readwrite, copy, null_resettable) NSString *latest;

@end

#pragma mark - ReqUpdate

typedef GPB_ENUM(ReqUpdate_FieldNumber) {
  ReqUpdate_FieldNumber_UpdateType = 1,
  ReqUpdate_FieldNumber_UpdateId = 2,
};

/**
 * 会话请求的信息
 **/
@interface ReqUpdate : GPBMessage

/** 更新的类型 */
@property(nonatomic, readwrite) int32_t updateType;

/** 更新的ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *updateId;

@end

#pragma mark - ReqReceipt

typedef GPB_ENUM(ReqReceipt_FieldNumber) {
  ReqReceipt_FieldNumber_ReceiptType = 1,
  ReqReceipt_FieldNumber_ReceiptId = 2,
};

/**
 * 回执消息
 **/
@interface ReqReceipt : GPBMessage

/** 回执 */
@property(nonatomic, readwrite) int32_t receiptType;

/** 回执的ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *receiptId;

@end

#pragma mark - Session

typedef GPB_ENUM(Session_FieldNumber) {
  Session_FieldNumber_SessionId = 1,
  Session_FieldNumber_SessionExtendId = 2,
  Session_FieldNumber_SessionType = 3,
  Session_FieldNumber_SessionName = 4,
  Session_FieldNumber_SessionImage = 5,
  Session_FieldNumber_SessionOffset = 6,
  Session_FieldNumber_SessionStamp = 7,
  Session_FieldNumber_SessionCreateDate = 8,
  Session_FieldNumber_SessionCreateUser = 9,
  Session_FieldNumber_SessionDeleted = 10,
  Session_FieldNumber_SessionDeletedDate = 11,
  Session_FieldNumber_Users = 12,
};

/**
 * 会话返回的信息
 **/
@interface Session : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionExtendId;

@property(nonatomic, readwrite) int32_t sessionType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionImage;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionOffset;

@property(nonatomic, readwrite) int32_t sessionStamp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionCreateDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionCreateUser;

@property(nonatomic, readwrite) int32_t sessionDeleted;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionDeletedDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *users;

@end

#pragma mark - Route

typedef GPB_ENUM(Route_FieldNumber) {
  Route_FieldNumber_UserId = 1,
  Route_FieldNumber_Device = 2,
  Route_FieldNumber_Pushid = 3,
  Route_FieldNumber_PushType = 4,
  Route_FieldNumber_Time = 5,
};

/**
 * 路由
 **/
@interface Route : GPBMessage

/** 用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 用户设备 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *device;

/** 推送ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pushid;

/** 推送类型 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pushType;

/** 时间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *time;

@end

#pragma mark - Message

typedef GPB_ENUM(Message_FieldNumber) {
  Message_FieldNumber_MessageId = 1,
  Message_FieldNumber_MessageSession = 2,
  Message_FieldNumber_MessageSessionType = 3,
  Message_FieldNumber_MessageSessionOffset = 4,
  Message_FieldNumber_MessageTableSeq = 5,
  Message_FieldNumber_MessageType = 6,
  Message_FieldNumber_MessageSend = 7,
  Message_FieldNumber_MessageSendExtendid = 8,
  Message_FieldNumber_MessageRecieve = 9,
  Message_FieldNumber_MessageRecieveExtendid = 10,
  Message_FieldNumber_MessageContent = 11,
  Message_FieldNumber_MessageSended = 12,
  Message_FieldNumber_MessageReaded = 13,
  Message_FieldNumber_MessageDate = 14,
  Message_FieldNumber_MessageDeleted = 15,
  Message_FieldNumber_MessageDeletedDate = 16,
};

/**
 * 消息
 **/
@interface Message : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageSession;

@property(nonatomic, readwrite) int32_t messageSessionType;

@property(nonatomic, readwrite) int32_t messageSessionOffset;

@property(nonatomic, readwrite) int32_t messageTableSeq;

@property(nonatomic, readwrite) int32_t messageType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageSend;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageSendExtendid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageRecieve;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageRecieveExtendid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageContent;

@property(nonatomic, readwrite) int32_t messageSended;

@property(nonatomic, readwrite) int32_t messageReaded;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageDate;

@property(nonatomic, readwrite) int32_t messageDeleted;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageDeletedDate;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
