// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flappy.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "Flappy.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - FlappyRoot

@implementation FlappyRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - FlappyRoot_FileDescriptor

static GPBFileDescriptor *FlappyRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - FlappyRequest

@implementation FlappyRequest

@dynamic type;
@dynamic latest;
@dynamic hasMsg, msg;
@dynamic hasLogin, login;

typedef struct FlappyRequest__storage_ {
  uint32_t _has_storage_[1];
  int32_t type;
  NSString *latest;
  Message *msg;
  LoginInfo *login;
} FlappyRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = FlappyRequest_FieldNumber_Type,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(FlappyRequest__storage_, type),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "latest",
        .dataTypeSpecific.className = NULL,
        .number = FlappyRequest_FieldNumber_Latest,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(FlappyRequest__storage_, latest),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "msg",
        .dataTypeSpecific.className = GPBStringifySymbol(Message),
        .number = FlappyRequest_FieldNumber_Msg,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(FlappyRequest__storage_, msg),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "login",
        .dataTypeSpecific.className = GPBStringifySymbol(LoginInfo),
        .number = FlappyRequest_FieldNumber_Login,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(FlappyRequest__storage_, login),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[FlappyRequest class]
                                     rootClass:[FlappyRoot class]
                                          file:FlappyRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(FlappyRequest__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - FlappyResponse

@implementation FlappyResponse

@dynamic type;
@dynamic msgArray, msgArray_Count;

typedef struct FlappyResponse__storage_ {
  uint32_t _has_storage_[1];
  int32_t type;
  NSMutableArray *msgArray;
} FlappyResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = FlappyResponse_FieldNumber_Type,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(FlappyResponse__storage_, type),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "msgArray",
        .dataTypeSpecific.className = GPBStringifySymbol(Message),
        .number = FlappyResponse_FieldNumber_MsgArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(FlappyResponse__storage_, msgArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[FlappyResponse class]
                                     rootClass:[FlappyRoot class]
                                          file:FlappyRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(FlappyResponse__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - KafkaMsg

@implementation KafkaMsg

@dynamic type;
@dynamic routeArray, routeArray_Count;
@dynamic hasMsg, msg;

typedef struct KafkaMsg__storage_ {
  uint32_t _has_storage_[1];
  int32_t type;
  NSMutableArray *routeArray;
  Message *msg;
} KafkaMsg__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = KafkaMsg_FieldNumber_Type,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(KafkaMsg__storage_, type),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "routeArray",
        .dataTypeSpecific.className = GPBStringifySymbol(Route),
        .number = KafkaMsg_FieldNumber_RouteArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(KafkaMsg__storage_, routeArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "msg",
        .dataTypeSpecific.className = GPBStringifySymbol(Message),
        .number = KafkaMsg_FieldNumber_Msg,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(KafkaMsg__storage_, msg),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[KafkaMsg class]
                                     rootClass:[FlappyRoot class]
                                          file:FlappyRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(KafkaMsg__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Route

@implementation Route

@dynamic userId;
@dynamic device;
@dynamic pushid;
@dynamic time;

typedef struct Route__storage_ {
  uint32_t _has_storage_[1];
  NSString *userId;
  NSString *device;
  NSString *pushid;
  NSString *time;
} Route__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = Route_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Route__storage_, userId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "device",
        .dataTypeSpecific.className = NULL,
        .number = Route_FieldNumber_Device,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Route__storage_, device),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "pushid",
        .dataTypeSpecific.className = NULL,
        .number = Route_FieldNumber_Pushid,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Route__storage_, pushid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "time",
        .dataTypeSpecific.className = NULL,
        .number = Route_FieldNumber_Time,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Route__storage_, time),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Route class]
                                     rootClass:[FlappyRoot class]
                                          file:FlappyRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Route__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\005A\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Message

@implementation Message

@dynamic messageId;
@dynamic messageSession;
@dynamic messageSessionType;
@dynamic messageSessionOffset;
@dynamic messageTableSeq;
@dynamic messageType;
@dynamic messageSend;
@dynamic messageRecieve;
@dynamic messageContent;
@dynamic messageSended;
@dynamic messageReaded;
@dynamic messageDate;
@dynamic messageDeleted;
@dynamic messageDeletedDate;

typedef struct Message__storage_ {
  uint32_t _has_storage_[1];
  int32_t messageSessionType;
  int32_t messageSessionOffset;
  int32_t messageType;
  int32_t messageSended;
  int32_t messageReaded;
  int32_t messageDeleted;
  NSString *messageId;
  NSString *messageSession;
  NSString *messageTableSeq;
  NSString *messageSend;
  NSString *messageRecieve;
  NSString *messageContent;
  NSString *messageDate;
  NSString *messageDeletedDate;
} Message__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "messageId",
        .dataTypeSpecific.className = NULL,
        .number = Message_FieldNumber_MessageId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Message__storage_, messageId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "messageSession",
        .dataTypeSpecific.className = NULL,
        .number = Message_FieldNumber_MessageSession,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Message__storage_, messageSession),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "messageSessionType",
        .dataTypeSpecific.className = NULL,
        .number = Message_FieldNumber_MessageSessionType,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Message__storage_, messageSessionType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "messageSessionOffset",
        .dataTypeSpecific.className = NULL,
        .number = Message_FieldNumber_MessageSessionOffset,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Message__storage_, messageSessionOffset),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "messageTableSeq",
        .dataTypeSpecific.className = NULL,
        .number = Message_FieldNumber_MessageTableSeq,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(Message__storage_, messageTableSeq),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "messageType",
        .dataTypeSpecific.className = NULL,
        .number = Message_FieldNumber_MessageType,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(Message__storage_, messageType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "messageSend",
        .dataTypeSpecific.className = NULL,
        .number = Message_FieldNumber_MessageSend,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(Message__storage_, messageSend),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "messageRecieve",
        .dataTypeSpecific.className = NULL,
        .number = Message_FieldNumber_MessageRecieve,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(Message__storage_, messageRecieve),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "messageContent",
        .dataTypeSpecific.className = NULL,
        .number = Message_FieldNumber_MessageContent,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(Message__storage_, messageContent),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "messageSended",
        .dataTypeSpecific.className = NULL,
        .number = Message_FieldNumber_MessageSended,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(Message__storage_, messageSended),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "messageReaded",
        .dataTypeSpecific.className = NULL,
        .number = Message_FieldNumber_MessageReaded,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(Message__storage_, messageReaded),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "messageDate",
        .dataTypeSpecific.className = NULL,
        .number = Message_FieldNumber_MessageDate,
        .hasIndex = 11,
        .offset = (uint32_t)offsetof(Message__storage_, messageDate),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "messageDeleted",
        .dataTypeSpecific.className = NULL,
        .number = Message_FieldNumber_MessageDeleted,
        .hasIndex = 12,
        .offset = (uint32_t)offsetof(Message__storage_, messageDeleted),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "messageDeletedDate",
        .dataTypeSpecific.className = NULL,
        .number = Message_FieldNumber_MessageDeletedDate,
        .hasIndex = 13,
        .offset = (uint32_t)offsetof(Message__storage_, messageDeletedDate),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Message class]
                                     rootClass:[FlappyRoot class]
                                          file:FlappyRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Message__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\016\001\t\000\002\016\000\003\022\000\004\024\000\005\017\000\006\013\000\007\013\000\010\016\000\t\016\000\n\r\000\013\r\000\014\013\000\r\016\000"
        "\016\022\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - LoginInfo

@implementation LoginInfo

@dynamic userId;
@dynamic device;
@dynamic pushid;

typedef struct LoginInfo__storage_ {
  uint32_t _has_storage_[1];
  NSString *userId;
  NSString *device;
  NSString *pushid;
} LoginInfo__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = LoginInfo_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(LoginInfo__storage_, userId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "device",
        .dataTypeSpecific.className = NULL,
        .number = LoginInfo_FieldNumber_Device,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(LoginInfo__storage_, device),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "pushid",
        .dataTypeSpecific.className = NULL,
        .number = LoginInfo_FieldNumber_Pushid,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(LoginInfo__storage_, pushid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[LoginInfo class]
                                     rootClass:[FlappyRoot class]
                                          file:FlappyRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(LoginInfo__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\005A\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
