use_frameworks!

platform :ios, '9.0'

target 'flappyim_Example' do
  pod 'flappyim', :path => '../'

  target 'flappyim_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
               end
          end
   end
end
